version: '3'
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db_name
  api:
    image: api_image_name
    ports:
      - '3000:3000'
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
  dashboard:
    image: dashboard_image_name
    ports:
      - '80:3000'
    networks:
      - webnet
networks:
  webnet:
