version: '3'
services:
  redis:
    image: redis
    networks:
      - default_network
  db:
    image: postgres
    networks:
      - default_network
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  api:
    build: ./packages/api
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'
    networks:
      - default_network
    environment:
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: redis
      REDIS_KEY_PREFIX: ${REDIS_KEY_PREFIX}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_TTL: ${JWT_ACCESS_TOKEN_TTL}
  dashboard:
    build:
      context: .
      dockerfile: ./packages/dashboard/Dockerfile
    depends_on:
      - api
    ports:
      - 8080:8080
    networks:
      - default_network
    environment:
      VITE_SERVER_HOST: api
      VITE_SERVER_PORT: 3000

networks:
  default_network:
    driver: bridge
